apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    component: mariadb
spec:
  selector:
    matchLabels:
      component: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: mariadb
    spec:
      containers:
        - image: mariadb:10.3.34
          name: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: pass
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: vol-mariadb
              mountPath: /var/lib/mysql
      volumes:
        - name: vol-mariadb
          persistentVolumeClaim:
            claimName: pvc-mariadb
