apiVersion: apps/v1
kind: Deployment
metadata:
  name: moc-xdmod
spec:
  selector:
    matchLabels:
      component: xdmod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: xdmod
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/test001/moc-xdmod
          name: xdmod-debug
          imagePullPolicy: IfNotPresent
          command:
            - "sleep"
          args:
            - "10000"
          volumeMounts:
            - name: xdmod-log
              mountPath: /var/log/xdmod
            - name: vol-xdmod-conf
              mountPath: /etc/xdmod
            - name: vol-xdmod-src
              mountPath: /usr/share/xdmod
      initContainers:
        - image: image-registry.openshift-image-registry.svc:5000/test001/moc-xdmod
          name: xdmod-init-1
          imagePullPolicy: IfNotPresent
          command:
            - "/usr/bin/xdmod-init"
          volumeMounts:
            - name: vol-xdmod-conf
              mountPath: /mnt/xdmod_conf
            - name: vol-xdmod-src
              mountPath: /mnt/xdmod_src
            - name: vol-xdmod-init
              mountPath: /root/xdmod_init
      volumes:
        - name: vol-xdmod-conf
          persistentVolumeClaim:
            claimName: pvc-xdmod-conf
        - name: vol-xdmod-src
          persistentVolumeClaim:
            claimName: pvc-xdmod-src
        - name: vol-xdmod-init
          configMap:
            items:
              - key: xdmod_init.json
                path: xdmod_init.json
            name: cm-xdmod-init-json
        - name: xdmod-log
          emptyDir: {}
